blank_issues_enabled: true
contact_links:
  - name: Group Support
    url: https://t.me/pantekyks
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: Not to public
    about: Documentation for getting started with bot.
